[tool.poetry]
name = "repl_python3_crawling-chigastoken"
version = "0.1.0"
description = ""
authors = ["idria <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pymysql = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
